import Head from "next/head";
import {
  AiFillInstagram,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/profilepic.png";
import Image from "next/image";
import web1 from "../public/fableland/web1.gif";
import web2 from "../public/fableland/web2.gif";
import web3 from "../public/fableland/web3.gif";
import web4 from "../public/fableland/web4.gif";
import web5 from "../public/fableland/web5.mp4";
import resume from "../public/kaztaharaedmondsresume.pdf";





export default function FableLand( props ) {
  const [darkMode, setDarkMode] = useState(true);



  const images = [
    { src: web1 },
    { src: web2 },
    { src: web3 },
    { src: web4 },
  ];

  

  const renderImages = () => {
    return images.map((image, index) => {
      return (
        <div key={index} className="basis-1/3 flex-1 ">
          <div className="image-container">
            <Image
              className="rounded-lg object-cover"
              width={"100%"}
              height={"75%"}
              layout="responsive"
              src={image.src}
            />
          </div>
        </div>
      );
    });
  }


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kaz Tahara-Edmonds Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="">
          <nav className="py-10 mb-0 flex justify-between dark:text-white">
            <button className="text-xl" onClick={() => props.setPage('home')}>Home</button>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href={resume}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex flex-wrap">
            <div className="w-full md:w-1/3 p-25n py-10 md:py-0">
              <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-lg w-80 h-80 relative overflow-hidden mt-2 md:h-96 md:w-96">
                <Image src={deved} layout="fill" objectFit="cover" />
              </div>
            </div>
            <div className="w-full md:w-2/3 p-20 py-200">
              <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
                FABLELAND
              </h2>
              <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
                Game Developer and Software Engineer.
              </h3>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl md:text-xl">
                Welcome to my portfolio! I started making games 
                at the age of 12 and have been passionate about <span className="text-teal-500"> bringing the worlds
                of my imagination to reality </span> ever since. All programming and art was 
                done entirely by me. Thank you for visiting, and I hope you enjoy 
                exploring 
                my games as much as I enjoyed creating them.
              </p>
            </div>
          </div>
        </section>
        <section className="">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {renderImages()}

            <div key={index} className="basis-1/3 flex-1 ">
          <div className="image-container">
            <video
                className="rounded-lg object-cover"
                width={"100%"}
                height={"75%"}
                layout="responsive"
                src={web5}
                />
              </div>
            </div>
          
          </div>
        </section>
      </main>
    </div>
  );
}
